name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          template: classic
          base: activity, metadata
          config_timezone: Europe/Moscow
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: issue, pr, review
          plugin_activity_limit: 5
          plugin_activity_load: 300
          plugin_activity_skipped: ApostolFet/*
          plugin_activity_visibility: public
          plugin_followup: yes
          plugin_followup_indepth: yes
          plugin_followup_sections: user
          plugin_notable: yes
          plugin_notable_filter: stars:>300
          plugin_notable_from: all
          plugin_notable_indepth: yes
          plugin_notable_repositories: yes
          plugin_notable_types: commit,pull_request,issue
          repositories_forks: yes
